name: Generate Pac-Man Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: publish-output
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - name: Generate Pac-Man graph
        uses: abozanona/pacman-contribution-graph@main
        with: { github_user_name: lkavindu }

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
