name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # daily at 00:00 UTC
  workflow_dispatch:       # allow manual runs
  push:
    branches: [ main ]     # also run on pushes to main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Generate Pac-Man graph
        uses: abozanona/pacman-contribution-graph@v1
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: List generated files (debug)
        run: |
          find . -maxdepth 5 -type f -name "pacman-contribution-graph*.svg" -print || true

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

